# Generated by Django 4.2.7 on 2023-11-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('project', 'Project'), ('product', 'Product'), ('application', 'Application')], max_length=50),
        ),
    ]
